$(function(){
    checkNull($('#login'));
    $('.submit').click(function(){
        console.log($('input[name=username]').val());
        console.log($('input[name=password]').val());
        window.sessionStorage.setItem('username',$('input[name=username]').val());
        window.sessionStorage.setItem('password',$('input[name=password]').val());
        $.ajax({
            url:'/login',
            type:'POST',
            beforeSend:function(XML){
                XML.setRequestHeader('username',$('input[name=username]').val());
                XML.setRequestHeader('password',$('input[name=password]').val());
            },
            success:function(response){
                console.log(response);
            }
        });

    });
});
