$(function(){
    checkNull($('#login'));
    $('.submit').click(function(){
        window.sessionStorage.setItem('username',$('input[name=username]').val());
        window.sessionStorage.setItem('password',$('input[name=password]').val());
        $.ajax({
            url:'/login',
            type:'POST',
            beforeSend:function(XML){
                XML.setHttpRequest('username',window.username);
                XML.setHttpRequest('password',window.password);
            },
            success:function(response){
                console.log(response);
            }
        });
    });
});
