$(function(){
    checkNull($('#login'));
    $('.submit').click(function(){
        console.log($('input[name=username]').val());
        console.log($('input[name=password]').val());
        window.sessionStorage.setItem('username',$('input[name=username]').val());
        window.sessionStorage.setItem('password',$('input[name=password]').val());
        ajaxHeader('/login',function(response){
            console.log(response);
        });
    });
});
